# Generated by Django 4.1.1 on 2022-10-25 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=32, verbose_name='titulo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion')),
            ],
            options={
                'verbose_name': 'Etiqueta de estado',
                'verbose_name_plural': 'Etiquetas de estado',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EtiquetaImportancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=32, verbose_name='titulo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion')),
            ],
            options={
                'verbose_name': 'Etiqueta de importancia',
                'verbose_name_plural': 'Etiquetas de importancia',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256, verbose_name='Titulo')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('fecha_inicio', models.DateField()),
                ('fecha_limite', models.DateField(verbose_name='fecha limite')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha actualizacion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.etiquetaestado')),
                ('importancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.etiquetaimportancia')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
