# Generated by Django 4.1.1 on 2022-11-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradablog',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Entrada de blog', 'verbose_name_plural': 'Entradas de blog'},
        ),
    ]
