# Generated by Django 4.1.1 on 2022-11-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_entradablog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradablog',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha actualizacion'),
        ),
    ]
